language: python
python:
  - 3.4
script: make test
notifications:
  email: false
install:
  - psql -c 'CREATE DATABASE pgcrypto_fields' -U postgres
  - pip install -r requirements.txt
  - pip install $DJANGO
env:
  matrix:
    - DJANGO='django>=1.7,<1.8'
    - DJANGO='--upgrade --pre django'
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO='--upgrade --pre django'
